### ISSUE TITLE
Does message_bus work on Heroku?

### ISSUE THREAD

**Issue by samratjp** [SamSaffron/message_bus#10]
Just curious to see how Message Bus would work with a multiple server setup on Heroku?

Also, is it possible to have auth with Message Bus for private channels?

Thanks!

**Comment by jemminger** [comment]
Bump...I've got Message Bus running locally on thin and local redis with no problems,  but I cannot get it to work on Heroku with passenger and redis cloud.  

What's more strange is that I cannot get MessageBus to work in the heroku console via my mixin, but I /can/ get it to work calling it directly.

E.g., this does not work via `heroku run rails c`:
```ruby
module BusDriver
  def broadcast_channel(channel, event_name, payload)
    Rails.logger.info "
    BusDriver#broadcast_channel: #{channel}, #{event_name}, #{payload.inspect}
    "
    MessageBus.publish "/#{channel}", { event: event_name, payload: payload }
  end
end

class Foo
  include BusDriver
end

foo = Foo.new
foo.broadcast_channel "my-subscribed-id", "some.event", { some: "data" }
```

When I run the code above, I'll see the log info, but I get nothing at all over the polling channel in my browser.  Mind you, the code above works as expected locally.


But this /does/ work:
```ruby
MessageBus.publish "my-subscribed-id", { event_name: "some.event", payload: { some: "data" } }
```

When I run this code, I DO get the expected response in the polling channel.

**Comment by SamSaffron** [comment]
Is there something different about the redis or passenger that heroku have
installed @schneems? Does it support pub/sub?

Does this issue also happen in unicorn+heroku?

**Comment by schneems** [comment]
We don't do anything special that I know of. I know of people using pub/sub with redis on Heroku.

**Comment by jemminger** [comment]
@SamSaffron I made a test app using Puma, and it seems to work, though I don't seem to get the messages pushed until the current poll ends:  https://bitbucket.org/jemminger/message-bus-puma

Am I doing it right?

**Comment by SamSaffron** [comment]
Sounds to me like pub/sub is not working right / or rack hijack is somehow
being disabled by heroku.

Can you try unicorn?

**Comment by jemminger** [comment]
Same behavior with unicorn: https://message-bus-unicorn.herokuapp.com/

https://bitbucket.org/jemminger/message-bus-unicorn

If you open the app in two windows, click the "new message" button a few times in one window, the results will not appear until the current poll connection is closed.

**Comment by jemminger** [comment]
@SamSaffron Scratch that last comment, the unicorn version is working as expected now.  I had forgotten the after_fork bit for unicorn:

```ruby
after_fork do |server, worker|
  MessageBus.after_fork
end
```

Is there a similar thing necessary for puma?

**Comment by jemminger** [comment]
I'll just continue to answer myself here :smile: 

Puma working now as expected, added `MessageBus.after_fork` to the `on_worker_boot` and `on_restart` blocks of the puma config.

**Comment by schneems** [comment]
@jemminger so sounds like things are working? Can we close the issue? Also maybe there's a doc PR you could make to clear up the issue for the next dev?

**Comment by jemminger** [comment]
@schneems Yes, go ahead and close this.  I'll try to put together a doc PR in the near future.

**Comment by SamSaffron** [comment]
I will go ahead and close it :) happy you figured this out, a PR to help out with doco here is totally welcome and would be super helpful.

Unfortunately there is no super clean way of getting an after_fork callback from ruby. We really need that built in to ruby.

**Comment by ffabreti** [comment]
@jemminger: 
Do we still need `MessageBus.after_fork` at `on_restart` blocks of the puma config ?
Is it only for heroky or is it general config ?

I don't see this on the actual version of the readme  (Apr/2016).

**Comment by jemminger** [comment]
From what I've read, only the `on_worker_boot` block should be necessary. 

I've only run puma on heroku, but if I understand correctly it's the multi-threaded mode that necessitates it, not specifically heroku.
