### ISSUE TITLE
Message_bus threads inside initializer and multi-threaded server

### ISSUE THREAD

**Issue by ffabreti** [SamSaffron/message_bus#102]
I have hit this situation described on #91 by derekyau: 

> ... when running message bus inside an initializer (like its done in the chat app example), since my web server is threaded (unicorn, etc.) I'm running into this issue where when a message comes in, multiple threads receive and process it at the same time. This often happens in the same action being called multiple times. I know I could guard in the code against this, but is there a better way of having only one thread take it and the rest don't receive it? Alternatively I guess I can setup a side process that is single threaded... whats best practice here?

The problem is reproducible running [this repo branch](https://github.com/ffabreti/message_bus-chat-example/tree/dupCallbackOnLeave)

I cannot understand why running this:
```
def expire_old_sessions
        $online.each do |name, time|
            if (Time.now - (5*60)) > time
                puts "SESSION EXPIRED FOR [#{name}] - #{time}"
                MessageBus.publish "/presence", {leave: name}
            end
        end
end
Thread.new do
    sleep 5
    while true
        expire_old_sessions
        sleep 2
    end
end
```
Leads to 2 callbacks calls at:
```
MessageBus.subscribe "/presence" do |msg|
        if user = msg.data["enter"]
            $online[user] = Time.now
            puts "/PRESENCE ENTER: #{user}"
        end
        if user = msg.data["leave"]
            if $online[user]
                puts "/PRESENCE LEAVE: #{user}"
                $online.delete user
            end
        end
end
```
Run Output:

> /home/fer/.rvm/rubies/ruby-2.0.0-p451/bin/ruby -e at_exit{sleep(1)};$stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /home/fer/.rvm/gems/ruby-2.0.0-p451/gems/ruby-debug-ide-0.4.23.beta1/bin/rdebug-ide --disable-int-handler --port 43547 --dispatcher-port 56329 -- /home/fer/RubymineProjects/messagebus-chat/bin/rails server -b 0.0.0.0 -p 3000 **-e fake_production**
Fast Debugger (ruby-debug-ide 0.4.23.beta1, debase 0.0.9) listens on 127.0.0.1:43547
=> Booting Puma
=> Rails 4.1.15 application starting in fake_production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
[27346] Puma starting in cluster mode...
[27346] * Version 3.3.0 (ruby 2.0.0-p451), codename: Jovial Platypus
[27346] * **Min threads: 1, max threads: 1**
[27346] * Environment: fake_production
[27346] * **Process workers: 1**
[27346] * Phased restart available
[27346] * Listening on tcp://0.0.0.0:3000
[27346] Use Ctrl-C to stop
Fast Debugger (ruby-debug-ide 0.4.23.beta1, debase 0.0.9) listens on 127.0.0.1:60480
========= ON WORKER BOOT ==============
[27346] - Worker 0 (pid: 27360) booted, phase: 0
SESSION EXPIRED FOR [donald] - 2016-04-26 00:30:35 -0300
/PRESENCE LEAVE: donald
SESSION EXPIRED FOR [hilary] - 2016-04-25 00:30:35 -0300
/PRESENCE LEAVE: donald
/PRESENCE LEAVE: hilary
/PRESENCE LEAVE: hilary
**SESSION EXPIRED FOR [jeffey] - 2016-04-27 00:25:45 -0300
/PRESENCE LEAVE: jeffey
/PRESENCE LEAVE: jeffey**
SESSION EXPIRED FOR [joseph] - 2016-04-27 00:25:55 -0300
/PRESENCE LEAVE: joseph
/PRESENCE LEAVE: joseph

I have tested it with redis and postgres backends.
Any clues?

**Comment by SamSaffron** [comment]
What is the message_id on these messages ? you getting duplicate message_ids?

**Comment by ffabreti** [comment]
Yes. Dup message_ids : 
```
[28832] Puma starting in cluster mode...
[28832] * Min threads: 1, max threads: 1
[28832] * Environment: fake_production
[28832] * Process workers: 1
[28832] * Phased restart available
========= ON WORKER BOOT ==============
[28832] - Worker 0 (pid: 28863) booted, phase: 0
SESSION EXPIRED FOR [donald] - 2016-04-26 09:15:03 -0300
/PRESENCE LEAVE: donald => msg: #<struct MessageBus::Message global_id=120, message_id=33, channel="/presence", data={"leave"=>"donald"}>
/PRESENCE LEAVE: donald => msg: #<struct MessageBus::Message global_id=120, message_id=33, channel="/presence", data={"leave"=>"donald"}>
SESSION EXPIRED FOR [hilary] - 2016-04-25 09:15:03 -0300
/PRESENCE LEAVE: hilary => msg: #<struct MessageBus::Message global_id=121, message_id=34, channel="/presence", data={"leave"=>"hilary"}>
/PRESENCE LEAVE: hilary => msg: #<struct MessageBus::Message global_id=121, message_id=34, channel="/presence", data={"leave"=>"hilary"}>
SESSION EXPIRED FOR [jeffey] - 2016-04-27 09:10:13 -0300
/PRESENCE LEAVE: jeffey => msg: #<struct MessageBus::Message global_id=122, message_id=35, channel="/presence", data={"leave"=>"jeffey"}>
/PRESENCE LEAVE: jeffey => msg: #<struct MessageBus::Message global_id=122, message_id=35, channel="/presence", data={"leave"=>"jeffey"}>
SESSION EXPIRED FOR [joseph] - 2016-04-27 09:10:23 -0300
/PRESENCE LEAVE: joseph => msg: #<struct MessageBus::Message global_id=123, message_id=36, channel="/presence", data={"leave"=>"joseph"}>
/PRESENCE LEAVE: joseph => msg: #<struct MessageBus::Message global_id=123, message_id=36, channel="/presence", data={"leave"=>"joseph"}>
```

**Comment by ffabreti** [comment]
I have noticed that when I comment `MessageBus.after_fork` on Rails `config/puma/fake_production.rb` I don't get duplicated callback calls.

```
#!/usr/bin/env puma
threads 1,1
workers 1
#preload_app!

on_worker_boot do
  ####MessageBus.after_fork
  puts '========= ON WORKER BOOT =============='
end
```

Output:
```
[24347] Puma starting in cluster mode...
[24347] * Version 3.3.0 (ruby 2.0.0-p451), codename: Jovial Platypus
[24347] * Min threads: 1, max threads: 1
[24347] * Environment: fake_production
[24347] * Process workers: 1
[24347] * Phased restart available
[24347] * Listening on tcp://0.0.0.0:3000
[24347] Use Ctrl-C to stop
Fast Debugger (ruby-debug-ide 0.4.23.beta1, debase 0.0.9) listens on 127.0.0.1:33150
========= ON WORKER BOOT ==============
[24347] - Worker 0 (pid: 24362) booted, phase: 0
SESSION EXPIRED FOR [donald] - 2016-04-26 16:46:49 -0300
SESSION EXPIRED FOR [hilary] - 2016-04-25 16:46:49 -0300
/PRESENCE LEAVE: donald => msg: #<struct MessageBus::Message global_id=360, message_id=150, channel="/presence", data={"leave"=>"donald"}>
/PRESENCE LEAVE: hilary => msg: #<struct MessageBus::Message global_id=361, message_id=151, channel="/presence", data={"leave"=>"hilary"}>
SESSION EXPIRED FOR [jeffey] - 2016-04-27 16:41:59 -0300
/PRESENCE LEAVE: jeffey => msg: #<struct MessageBus::Message global_id=362, message_id=152, channel="/presence", data={"leave"=>"jeffey"}>
SESSION EXPIRED FOR [joseph] - 2016-04-27 16:42:09 -0300
/PRESENCE LEAVE: joseph => msg: #<struct MessageBus::Message global_id=363, message_id=153, channel="/presence", data={"leave"=>"joseph"}>
```

**Comment by ffabreti** [comment]
I can also reproduce the problem with original `examples/chat/chat.rb`:

$ cat ../../../messagebus-chat/config/puma/fake_production.rb 
```
#!/usr/bin/env puma

threads 1,20
workers 2
# preload_app!

require 'message_bus'

on_worker_boot do
  MessageBus.after_fork
  puts '========= ON WORKER BOOT =============='
end
```
inside chat.rb:
```
MessageBus.subscribe "/presence" do |msg|
  puts "PRESENCE: #{msg}"
```
$ bundle exec puma -C ../../../messagebus-chat/config/puma/fake_production.rb 

```
[5565] Puma starting in cluster mode...
[5565] * Version 3.4.0 (ruby 2.0.0-p451), codename: Owl Bowl Brawl
[5565] * Min threads: 1, max threads: 20
[5565] * Environment: development
[5565] * Process workers: 2
[5565] * Phased restart available
[5565] * Listening on tcp://0.0.0.0:9292
[5565] Use Ctrl-C to stop
========= ON WORKER BOOT ======================= ON WORKER BOOT ==============

[5565] - Worker 1 (pid: 5574) booted, phase: 0
[5565] - Worker 0 (pid: 5570) booted, phase: 0
PRESENCE: #<struct MessageBus::Message global_id=566, message_id=250, channel="/presence", data={"leave"=>"DRI"}>
PRESENCE: #<struct MessageBus::Message global_id=566, message_id=250, channel="/presence", data={"leave"=>"DRI"}>
PRESENCE: #<struct MessageBus::Message global_id=567, message_id=251, channel="/presence", data={"enter"=>"DRI"}>
PRESENCE: #<struct MessageBus::Message global_id=567, message_id=251, channel="/presence", data={"enter"=>"DRI"}>
^C[5565] - Gracefully shutting down workers...
[5565] === puma shutdown: 2016-04-27 19:07:43 -0300 ===
[5565] - Goodbye!
$ ^C


```

**Comment by ffabreti** [comment]
From what I can understand, the `on_worker_boot` puma method only applies when you config `workers`, what leads to `MessageBus.after_fork` so that MessageBus code can be re-set on the new forked process. 

That way, it is understandable that a new `$online` presence hash will be created on the new forked process and there will be no thread safety issues. Those duplicated presence hashes will be syncronized by one of the processes publishing to /presence channel, since all of then subscribe to that channel and update their own presence hash.
I've made tests with puma config `threads 1,1  workers 1` where I can confirm by inspecting objects and threads
```
/PRESENCE LEAVE: user_26 => Thread:#<Thread:0x00000005211858> => $online:40236000 => $online[user]:50470540 => global/msg id:6395/5989
/PRESENCE LEAVE: user_26 => Thread:#<Thread:0x00000004cbe5e0> => $online:40236000 => $online[user]:48672400 => global/msg id:6395/5989
```
I just don't understand how come $online object_id be the same on different workers ( I see two puma Linux process on `ps`):
```
ps ax | grep puma
 5772 ?        Sl     0:03 puma 3.3.0 (tcp://0.0.0.0:3000) [message_bus-chat-example]
 5788 ?        Sl     0:06 puma: cluster worker 0: 5772 [message_bus-chat-example]

```
But `threads 1,16` on puma config may cause thread safety issues because they will be accessing a same copy of `$online` which is not thread safe. One solution would be to make it thread-safe what implies filling the code that read/write $online with mutexes.

**Comment by SamSaffron** [comment]
I think you are calling the initializer after fork, message bus maintains all subscriptions after fork. 

Simplest fix is to only subscribe if you are not already subscribed (setting a global after you subscribe)

**Comment by ffabreti** [comment]
But, wait... isn't true that:
- when puma forks, 2 processes run isolated (one doesn't see the global vars of another) ?
- the only way those 2 processes would communicate would be thru subscribing to message_bus channels ?

**Comment by SamSaffron** [comment]
- Puma creates a master process, it subscribes
- Then it forks a bunch of children all are already subscribed 

Data from master process is copied into all children, by design. Children can not amend master, master can no longer amend children once forked.

**Comment by ffabreti** [comment]
Well, as I said, I dont think that matters where I call the code actually on an initializer, because both puma workers need to run the initializer code or they won't work!
In fact, what I thought was a bug, is just normal behaviour, because at server, when a worker is forked, it needs to have the exactly code its parent has running. In fact there will be as many copies of `$online` presence hashes as the number of workers and all of those copies get in sync thru REDIS or Postgres (whatever backend you choosed to run).
When a JS-Client pools the server, it will get connected to one of the puma workers and there will be no duplicated messages. Dup messages only appear on the server code, because of the forked code.

I think I am done understanding this, sorry for the newbie question and thank you for your comments.
If you'd like to add anything... or you can close this.

**Comment by SamSaffron** [comment]
np, glad you worked it out
