### ISSUE TITLE
Mention that messages are JSON-encoded internally in documentation

### ISSUE THREAD

**Issue by kwando** [SamSaffron/message_bus#106]
I tried to use symbols as group_ids which turns out not to work since group_ids and user_ids are JSON encoded/decoded internally.. this should probably be mentioned in the docs somewhere. 
Alternatively one can use `Marsal` instead, if human readability of the encoded value is not important.

**Comment by SamSaffron** [comment]
Ideally I would prefer to keep this in JSON, it is more interoperable. no way of communicating the concept of key to a JavaScript app cleanly.  

Feel free to do a PR to explain
