### ISSUE TITLE
Firefox long polling performance fix

### ISSUE THREAD

**Issue by washu** [SamSaffron/message_bus#109]
add async: true to the ajax request object. Firefox seems to ignore the default so explicitly setting the flag enables the intended behavior better
message-bus.js around line 188

**Comment by SamSaffron** [comment]
Can you submit a PR for this? I did test in FF and chunked encoding seemed to work, what in particular are you noticing?

**Comment by washu** [comment]
i submitted a PR, what i see is during a long poll processing that occurs while another ajax call is processing you get a ui hang, when i added the async:true instead of just letting the implicit true to ajax call run i dont get those hangs anymore.
https://github.com/SamSaffron/message_bus/pull/110

**Comment by SamSaffron** [comment]
this was merged :+1:
