### ISSUE TITLE
How to access MessageBus endpoint inside tests ....

### ISSUE THREAD

**Issue by ffabreti** [SamSaffron/message_bus#111]
... so that ruby client can connect to server ?

Something like:
```
        mb_client = MessageBus::Client.new("endpoint ?????")
        lockme = true

        mb_client.subscribe("/presence/user") do |msg|
            puts "presence: #{msg}"
            lockme = false
            assert_equal @user.id, msg['user_id']

        end
        while lockme
            sleep 1
        end
```

**Comment by SamSaffron** [comment]
If you need you can create concrete message_bus classes as opposed to using the singleton, just have a look at the tests here.

At Discourse when running the test suite we don't bother and simply use the singleton for everything.

**Comment by ffabreti** [comment]
Ah.. got it. Thanks!

**Comment by ffabreti** [comment]
Sorry for being a pain...
but, everything works, except pooling. When I do:
```
    test 'user should receive message from pooling' do
        #enter normal user
        post :enter, @remote_params
        assert_response :success

        client_id = 'usr-usr-usr-usr'
        post "/message-bus/#{client_id}", {
          '/presence/user' => nil
        }
        assert_response :success
    end
```
I get this error:

> Minitest::UnexpectedError: ActionController::UrlGenerationError: No route matches {:"/presence/user"=>nil, :action=>"/message-bus/usr-usr-usr-usr", :controller=>"/chat"}


I am using the middleware in application_controller.
Any ideas?
