### ISSUE TITLE
postgres to keep backlog and clear it at user request or expires it in 6 months

### ISSUE THREAD

**Issue by ffabreti** [SamSaffron/message_bus#112]
I have a chat use case where every user has its own channel (ex: `/message/user_746`) 
I am doing that because I want user to control when to clear its own channel backlog (or let it expires within 6 months)

reading postgres backend code, at class `MessageBus::Postgres::ReliablePubSub` we have some class variables taking care of backlog:
```
def initialize(config = {}, max_backlog_size = 1000)
    @config = config
    @max_backlog_size = max_backlog_size
    @max_global_backlog_size = 2000
    # after 7 days inactive backlogs will be removed
    @max_backlog_age = 604800
    @clear_every = config[:clear_every] || 1
  end
```
And on publish, we have the cleanup code:
```
def publish(channel, data, queue_in_memory=true)
    # ...
    if backlog_id % clear_every == 0
      client.clear_global_backlog(backlog_id, @max_global_backlog_size)
      client.expire(@max_backlog_age)
      client.clear_channel_backlog(channel, backlog_id, @max_backlog_size)
    end

    backlog_id
  end
```
Problem is, I can't fight `% clear_every == 0`, sooner or later it will pass.

Question:
    Even if I set `max_backlog_size` to 9223372036854775807 ([upper bigserial limit](http://www.postgresql.org/docs/9.4/static/datatype-numeric.html)), messages would still been cleared at the global `max_global_backlog_size` hardcoded limit (2000), right? ~~Or is there a way to set `max_global_backlog_size` at runtime?~~
Edit: I see I can set it thru: `MessageBus.reliable_pub_sub.max_global_backlog_size`

~~If I could~~ I can set `max_global_backlog_size` together with `max_backlog_size` to a max value, ~~I would~~ and still get inside the `clear_every if` and run the `expire` code.

Any better approaches?

As for letting the user clear its own channel backlog, ~~would also be nice to have that method inside Postgres adapter instead of running a SQL delete against the table outside of it.~~ Can I just use `MessageBus.reliable_pub_sub.clear_channel_backlog()` ?

**Comment by jeremyevans** [comment]
If you don't want to ever clear the backlog automatically, can't you just set :clear_every to 9223372036854775807?

**Comment by ffabreti** [comment]
I still want to `expire`. So I thought of setting `max_global_backlog_size` together with `max_backlog_size` to a max value. That way, I would still enter the `clear_every if` say every 100 publishes.

Would that looks ok ?
What about calling `MessageBus.reliable_pub_sub.clear_channel_backlog()` by hand?

I really don't want to break things in the future...

**Comment by SamSaffron** [comment]
@jeremyevans I am closing this for now. not sure there is anything we really need to do, running out of ids in practice will never happen
