### ISSUE TITLE
message_bus crashes rails server sporadically in development environment

### ISSUE THREAD

**Issue by uri** [SamSaffron/message_bus#115]
Hard to say what exactly is happening right before it crashes but it's happening consistently for our developers. Most of the devs do not actually interact with message_bus. The JavaScript client may be loading but that would be it.

Most common thing I hear is, "It crashes after a while." I don't usually have my server running all the time, but I have seen this happen firsthand.

Also we were using Passenger 4 up until recently and we were seeing the exact same behaviour.

- | version
---- | ----
ruby | 2.1.6-p336
puma | 3.4.0
rails | 4.1.14.2
message_bus | 81619838aa54313faf278831b092db6126d3fcd9 ([v2.0.0.beta.11](https://github.com/SamSaffron/message_bus/tree/v2.0.0.beta.11))

###### Puma crash

```
Global messages on 12953 timed out, restarting process
- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2016-06-17 12:09:40 -0400 ===
- Goodbye!
Exiting
```

###### Stack trace that follows

```
message_bus-81619838aa54/lib/message_bus.rb:484:in `kill': No such process (Errno::ESRCH)
      from message_bus-81619838aa54/lib/message_bus.rb:484:in `block (2 levels) in new_subscriber_thread'
      from message_bus-81619838aa54/lib/message_bus.rb:481:in `fork'
      from message_bus-81619838aa54/lib/message_bus.rb:481:in `block in new_subscriber_thread'
      from message_bus-81619838aa54/lib/message_bus/timer_thread.rb:98:in `call'
      from message_bus-81619838aa54/lib/message_bus/timer_thread.rb:98:in `do_work'
      from message_bus-81619838aa54/lib/message_bus/timer_thread.rb:29:in `block in initialize'
```

**Comment by SamSaffron** [comment]
the fix is fine, but I am concerned this is a different issue, maybe keepalive is not working for you in dev? you can disable that feature if you must.
