### ISSUE TITLE
How do JS-Clients get the last message Id for a channel ?

### ISSUE THREAD

**Issue by ffabreti** [SamSaffron/message_bus#118]
I have this code in the JS-Client:

```
var lastPresence = getLastPresenceIdFromLocalStorage() || 0;
MessageBus.subscribe('/presence/user', updateUserPresence, lastPresence );
function updateUserPresence(data) {
     console.log('Chat: updateUserPresence: ', data);
 }
```

It works, but I see that message-bus.js doesn't pass the last message Id to the callback, it pass only the payload (data).

I'd like to save the last message Id in the `lastPresence` variable which will be persisted to localStorage on exit or pause of the app.

**Could you please point me how to get the last message Id for a channel ?**

**Comment by SamSaffron** [comment]
yeah that id is opaque its not meant to matter, that said open to amending it so global id and local id are sent as params 2 and 3
