### ISSUE TITLE
Is it possible to suppress failed requests?

### ISSUE THREAD

**Issue by julik** [SamSaffron/message_bus#12]
I find my console is getting quite talkative. Like so:

https://www.dropbox.com/s/yrd2qsjysng4kw9/Screenshot%202014-02-18%2011.37.07.png

It's not quite clear what should I investigate when I get those failed requests. My server in dev is running on guard-rack via thin.

**Comment by SamSaffron** [comment]
I cleaned some of this up, and you can control logging level if you need extra fidelity.
