### ISSUE TITLE
'Synchronous' subscribe in js library

### ISSUE THREAD

**Issue by tim-vandecasteele** [SamSaffron/message_bus#122]
I'm trying to use message bus to poll for a status of a background job. The moment before I start the background job, I do `MessageBus.subscribe` on the relevant channel (MessageBus is already started before this, but I don't think this really matters). The job sometimes completes rather quickly, meaning that sometimes the message I'm looking for has come before the subscribe has actually happened. (I'm using message_bus 2.0.1).

Is there a way to make sure that I get all message as soon as I call subscribe?

**Comment by SamSaffron** [comment]
Sure, just specify the last id you got. If you subscribe at position 2 your will get all messages from position 2.

**Comment by tim-vandecasteele** [comment]
Of course, makes perfect sense. Didn't think about passing the id before starting the subscribe. Thanks for the great library!
