### ISSUE TITLE
uninitialized constant Redis::CommandError

### ISSUE THREAD

**Issue by pabloalr** [SamSaffron/message_bus#125]
I'm trying to publish using Redis backend, but it keeps throwing this error on lib/message_bus/backends/redis.rb:124.

Any clue?

**Comment by jeremyevans** [comment]
`Redis::CommandError` is defined by redis-rb (https://github.com/redis/redis-rb/blob/3ae7fbda312caba5668bedd2ecd1ab15ff0d975e/lib/redis/errors.rb#L18), which message_bus requires.   `Redis::CommandError` was added in redis-rb 3.0.0, so maybe you are using a version released before that (3.0.0 was released over 4 years ago)?  If so, please try upgrading redis-rb.

**Comment by pabloalr** [comment]
Indeed, that was the problem, I was still using redis-rb 2.2.2.

Thanks!
