### ISSUE TITLE
Feature Request: JS Message_bus client side message count

### ISSUE THREAD

**Issue by danweller18** [SamSaffron/message_bus#127]
Javascript message count would be useful when displaying messages. 

I noticed https://github.com/SamSaffron/message_bus/blob/master/assets/message-bus.js#L74
`callback.last_id = message.message_id;`, but I couldn't figure out how to get the id into a nice variable.

For example now I have to do this instead of just using the message count for each message. 

```javascript
  var page = 1;
  var msg_count = 1;
  var div = "#get"+page;
  MessageBus.subscribe('/my_channel:'+channel, function(msg) {
    var obj1 = msg_count % 3 == 0 ? true : false;
    var obj2 = msg_count % 3 == 1 ? true : false;
    var obj3 = msg_count % 3 == 2 ? true : false;
    if ((page == 1) && obj2) {
      //do something
    }
    if (obj2) {
      //do something
    }
    if (page == 1) {
      //do something
    }
    if(obj2) {
      //do something
    } else if (obj3) {
      //do something
    } else if (obj1) {
      //do something
      page++;
      div = "#get"+page;
    }
    msg_count++;
  });```

**Comment by SamSaffron** [comment]
ouch that looks really fragile, cant you simply look at the channel name when deciding on dispatch?

**Comment by danweller18** [comment]
yes lol which is why I was hoping to use a message_id. I am using it to determine when to display attributes on the page. For example the first message sent will initialize divs and some headers on the page. Also some exchanges might contain a title, the actual message, or attributes about the message that I want to display.

**Comment by SamSaffron** [comment]
That is a bit of an odd design, why not introduce channels?

Regarding ids, the callback is invoked with (message, global_id,
message_id) so you can access this data as you wish.

**Comment by danweller18** [comment]
Thank you. I didn't realize that was possible.
