### ISSUE TITLE
Displaying all the messages -Feature or Bug (not sure)

### ISSUE THREAD

**Issue by danweller18** [SamSaffron/message_bus#128]
I thought message bus would start at message 0 and get every message as defined in `MessageBus.callbackInterval`. However sometimes message_bus will skip my messages. I think this is happening because multiple messages are added in between `MessageBus.callbackInterval`s.

Message_bus skips when my client JS looks like:
```javascript
MessageBus.subscribe('/status:'+channel, function(msg) {
  //do something
});
```

Message_bus does not skip when my client JS starts at message 0:
```javascript
MessageBus.subscribe('/status:'+channel, function(msg) {
  //do something
}, 0);
```

Why do I need to specify that message_bus start at message 0 in order to get everything?

**Comment by SamSaffron** [comment]
that is just how the API works, the most common use case is to subscribe
from now -> onwards.

defaulting to 0 would cater for an uncommon usage, every message in backlog
-> onwards.

**Comment by danweller18** [comment]
Got it, guess my usage is uncommon. Thanks!
