### ISSUE TITLE
Support different client/server locations

### ISSUE THREAD

**Issue by ericeslinger** [SamSaffron/message_bus#13]
I'll look into fixing this myself and submitting a PR, but it seems like message_bus isn't built for housing the client and server on different machines (I have a client front end that gets JSON api data from my api server and subscribes to an updates channel on the same server to get notified of changes).

While changing the relevant bit in line 112 from baseUrl to me.baseUrl allows me to say MessageBus.baseUrl = "http://api.example.com" in my app setup block, the message_bus middleware doesn't set CORS headers, so my client refuses to listen to message_bus.

**Comment by arcreative** [comment]
:+1: to this... Having to fork to add CORS headers!

**Comment by SamSaffron** [comment]
This is supported per: 

https://github.com/SamSaffron/message_bus/commit/1797337abb0fc27948adbfbfd7a0fbd11bc576a4

**Comment by arcreative** [comment]
Thanks @SamSaffron.

For others with this issue, it's probably worth mentioning/documenting the usage:

```ruby
MessageBus.extra_response_headers_lookup do |env|
  # Headers can be site-specific based on env
  [
      ['Access-Control-Allow-Origin', '*'],
      ['Access-Control-Allow-Headers', '*, x-silence-logger, authorization']
  ]
end
```
