### ISSUE TITLE
Delivering messages [] to client

### ISSUE THREAD

**Issue by kgish** [SamSaffron/message_bus#130]
In development mode my output gets garbled making it hard to view debug output because it is continuously scrolling out of view.

```
Delivering messages [] to client 22333977e6f845ac95a85d44cf9bcabe \
    for user 9697 (chunked)
```

Is there someway I can disable this?

**Comment by SamSaffron** [comment]
Sure ... in your initializer do something like

logger = Logger.new(STDOUT)
logger.level = Logger::INFO
MessageBus.logger = logger

**Comment by kgish** [comment]
Which initializer? I would only like to do this when RAILS_ENV=development

**Comment by kgish** [comment]
Never mind,  I put it in my `environments/development.rb` file and it works like a charm.
