### ISSUE TITLE
Possible to publish to MessageBus from background job?

### ISSUE THREAD

**Issue by cannikin** [SamSaffron/message_bus#131]
Sorry to open an issue for this since it's more of a question!

Assuming MessageBus is being backed by Redis, can I publish to the bus from a background process (like DelayedJob) and have any published messages be broadcast from the app servers? 

Actually the publishing of a message to the bus isn't what I'm worried about, it's the pulling them from the queue and broadcasting to users. I'm worried that when DelayedJob's daemon starts, MessageBus assumes it's running in an application process like any other, and starts pulling messages out of the queue and trying to publish them to users (which will never work because DJ isn't actually hooked up to the outside world).

Am I just mistaken thinking that DJ starts up Rails as a Rack app? I guess if Rack doesn't start then the MessageBus middleware is never invoked and there's no problem?

**Comment by SamSaffron** [comment]
This works fine. 

```
rails c
% MessageBus.publish "/channel", "payload"
```

You have to run a MessageBus.subscribe in server code to start up any subscription threads 

So yeah not expecting any issues and DJ can publish messages just fine cause it will go either via pg or redis depending on the adapter you are running :)
