### ISSUE TITLE
CORS configuration

### ISSUE THREAD

**Issue by bkeane** [SamSaffron/message_bus#135]
This may be a documentation request more than a feature request or issue. 

Is there a way to use rack-cors with message_bus? In testing, when I place:
```ruby
use Rack::Cors do
  allow do
    origins '*'
    resource '*', :headers => :any, :methods => :any
  end
end
```
in my config.ru, my routes accept cross origin, but the /message-bus/:id/poll route does not seem to inherit this rack config. I see preflight errors in the browser console, whereas the routes I have defined in my application code are returning properly.

Am I missing something right in front of me? Or am I trying to achieve something not intended to be supported?

Great project. Love using it.

**Comment by SamSaffron** [comment]
Thanks, 

message bus is usually earlier in the middleware stack and handles it this way:

https://github.com/discourse/discourse/blob/master/config/initializers/004-message_bus.rb#L44-L47

**Comment by SamSaffron** [comment]
@bkeane closing this, is that ok? perhaps send through a PR to document CORS?
