### ISSUE TITLE
Can we achieve user to user private chat through message bus? 

### ISSUE THREAD

**Issue by AnilKadiyala** [SamSaffron/message_bus#139]
Hi,  As per our requirement, we are trying to personalise the chat between the logged in user and the selected user,  by not broadcasting a messages to all the users in the group or category.

before doing that, want to check whether it possible with message bus to click on user of logged in user's choice and to have a private chat between both. 

awaiting for your reply, thanks in advance.

**Comment by SamSaffron** [comment]
Absolutely, be sure to read the README, you can send messages that only can be received by particular users.
