### ISSUE TITLE
Rails Installation Documentation

### ISSUE THREAD

**Issue by jmatsuba** [SamSaffron/message_bus#142]
This library looks great. I've managed to somewhat get it running on one of my projects, however, i've found the documentation not the best for a rails setup.

If resources permit, i would love to see a rails specific gem complete with a generator. Or at the very least more detailed rails setup information.

1) Install the gem
2) Copy `message-bus.js` to the `/app/assets/javascripts`
3) Add `//= require message-bus` to `application.js`
4) Setup a initializer that specifies the configuration

Am i missing anything?
What benefit does the Middleware setup provide?

**Comment by SamSaffron** [comment]
You should no need to copy any files ... step 2 is confusing to me.

**Comment by jmatsuba** [comment]
My bad, your right no need to copy anything. It was just something that was in the example app posted.
https://github.com/ffabreti/message_bus-chat-example/tree/master/app/assets/javascripts

I setup a new rails project and am trying to get things working.
https://github.com/jmatsuba/test-messagebus-app

If you have time and can advise what is missing, that would be appreciated. I can PR some improved documentation once i understand the process.

**Comment by jmatsuba** [comment]
Figured it out. Thanks for your help.
