### ISSUE TITLE
How does MessageBus handle long "time-outs"?

### ISSUE THREAD

**Issue by cmitz** [SamSaffron/message_bus#145]
Hey, we're having an issue with MessageBus on production, especially on mobile devices. We use a combination of Rails API and Ember (with JSONAPI).

The exact problem: sometimes when a user opens the website on their phone, after being on the background for some time, he gets logged out unexpectedly (probably by a 403). Me and my fellow students are struggling to nail the problem.

In my quest to solve the issue, I am now here. The question is: what does MessageBus do with long-polling and the browser being pushed to the background for a long time? Are pending requests just lost? 

If this is not the place to ask, I'm sorry :-)

**Comment by cmitz** [comment]
To get a more precies view of the event occuring, we think this is what happens:

1. User opens website on phone
1. User logs in (new bearer token)
1. User opens general chat
1. User sees some past chat messages (API)
1. User presses `home` on phone, or leaves the browser running in the background in another way
1. Meanwhile another user posts a message
1. The bearer token expires after 20 minutes
1. User opens the app again
1. ??
1. Ember automatically logs the user out

**Comment by SamSaffron** [comment]
First thing you want to confirm is that you are running on HTTPS, cause if you are not ... all bets are off. 

To answer your specifics here:

> what does MessageBus do with long-polling and the browser being pushed to the background for a long time? 

It does short polls every few minutes when it is in the background (this is configurable) 

> Are pending requests just lost?

No pending requests are lost, message bus always recovers backlog

**Comment by cmitz** [comment]
Thanks for your answer. I've been reading into the code since your answer, and our bug seems to be somewhere else then. I think Ember is doing some wonky stuff, so I think I need loads more error logging to be able to see what's happening.

Thanks again for your answers!
