### ISSUE TITLE
Guides and examples

### ISSUE THREAD

**Issue by feliperaul** [SamSaffron/message_bus#159]
I know this is something the mantainer asks for help in the Readme, but where can I learn more about this awesome gem for now?

For example, looking around in the web I found this:

```
# the last local id on the chuck channel
id = MessageBus.last_id('/chuck')
```
Source: https://meta.discourse.org/t/how-discourse-stays-online-message-bus-faye-long-polling/3238/7

It appears it's not documented anywhere, and it was something I was looking for to having for subscribing on the client side after the last_id the server found when rendering the page to the frontend (so that if new messages were posted during render, client would be up-to-date starting from the last_id that the server found when rendering the view).

But I still have a lot of questions on how to implement this in production in an efficient way ... 

- should I use one channel per user / model ? 
- What are the consequences of having unlimited channels, like one for each model uuid, or should I restrict my channels to just a few ? 
- Should I pass HTML/JSON as data to use it on the frontend for replacing the HTML view, or a best practice would be to just use the channel to notify the frontend of an update, and then the frontend fires a new request for getting the updated HTML via ajax for instance?

**Comment by SamSaffron** [comment]
I improved the readme a bit to cover data retention and add last_id
documentation, any extra improvements to the readme are totally welcome.

Regarding number of channels, it really depends on your data retention
concerns. More channels you add more data you retain in redis. performance
wise we poll on multiple channels in one call so there is no need cut down
on channel counts just to keep traffic down.

Regarding payload size, its a balancing act, on one hand you don't want to
trigger a thundering herd all asking app for the same payload at once. On
the other hand you don't want to store giant blobs in redis, especially if
you are doing catch up and may get multiple giant payloads on the client
side.

There is like a giant blog post in replying to all your concerns here :)
sorry for being brief. Readme PRs are totally welcome.
