### ISSUE TITLE
How to configure messagebus for running in rspec + capybara + selenium

### ISSUE THREAD

**Issue by cdrapier** [SamSaffron/message_bus#164]
Hi,

We have been using MessageBus in production for more than a year now and we are pretty happy with it, so first of all please let me thank you for the awesome gem!

Recently, after upgrading to from rails 4.2.X to rails 5.0.7 (maybe ?), we have been having more and more flickering specs that involves some data that should be updated by MessageBus (it might or might not be directly related to something inside MessageBus or to the way we are setting up our test environment)... So I was trying to dig in and see what is going on.

The first thing I found was that when we switched to MessageBus back then, we forced it to not use chunked encoding or long polling and poll every 200 ms in the test environment only, and I think the reason why we did this is because our feature specs (with Selenium, Capybara and Firefox) tend to wait for the page to load before performing actions (which is pretty standard as far as I understand). But it seems it is also waiting for the first polling to end to consider the page loaded if we use the same configuration as production (with long polling and chunked encoding). The reason of this is maybe because we are subscribing to channels as part of the page load, but that also sounds pretty standard to me.

In our JavaScript
```
$ ->
  elem = $("#notification_service")
  if elem.length > 0
    channel = elem.data 'channel'
    <% if Rails.env.test? %>
    MessageBus.enableChunkedEncoding = false
    MessageBus.enableLongPolling = false
    MessageBus.callbackInterval = 200
    <% end %>
    MessageBus.subscribe channel, (message) ->
```

In our configuration / initializer
```
      if Rails.env.test?
        message_bus_config.merge!(chunked_encoding_enabled: false)
      end
      if defined?(MessageBus)
        MessageBus.configure(message_bus_config)
        MessageBus.reliable_pub_sub.max_backlog_age = 21600
      end
```

We are using Rails 5.0.7, puma (for tests), redis 4, pretty much the latest rspec, capybara, selenium and gecko driver.

Did you see that kind of behavior before, or would you have any advice to deal with this? I tried to look in the documentation or in other issues but I couldn't find anything specific about feature specs that are using MessageBus. We saw that in the Discourse configuration there's the "keepalive_interval" that is set to -1 for tests, but I'm not sure if this is directly related to the issue we are facing.

Thanks in advance!

**Comment by SamSaffron** [comment]
Is there any way you can make a test case here that reproduces the issue? 

Losing messages is something that generally happens if you subscribe at position 0 cause then there are timing issue. I think the safest thing to do in tests is to always subscribe at an actual position that the payload of the html provides, that way you have a server and client in sync.

**Comment by cdrapier** [comment]
Thanks a lot for your answer. I have tried to dig this a bit further for days and I seem closer to finding what is wrong in our test. We were never subscribing at any position (as shown in the first snippet), and in some cases (particularly on CI or locally with the browser "minimized") it seems that the action in the test was done before message-bus could get the status... So as you just mentioned, we should probably try to always provide a starting position.

I also confirmed that in our case the additional client side configuration in tests was not necessary, and I want to dig a bit more about the server side one and find out why is that really needed.

**Comment by cdrapier** [comment]
I have tried to build a little test application that mimics our configuration in order to reproduce the "hanging for 20+ seconds" problem on the page load in capybara, but I failed to see that hanging problem appear on that dummy application (https://github.com/cdrapier/message_bus_capybara_test), so I assume this is a problem with something more complex on our part.

Sorry for the inappropriate issue then, and thanks a lot for helping with the 0 position matter!
