### ISSUE TITLE
We should ship an optional HTTP client

### ISSUE THREAD

**Issue by SamSaffron** [SamSaffron/message_bus#189]
@lowjoel built https://github.com/lowjoel/message_bus-client , @tgxworld is busy building something similar

I feel it makes much more sense just to ship an optional HTTP client with the repo, that way we can keep it working, even if we end up building two gems here from the single repo. 

`gem install message_bus-http_client`

```
require 'message_bus/http_client'
client = MessageBus::HttpClient.new('https://chat.samsaffron.com/')
client.subscribe('/test/channel') do |message|
   ...
end

client.unsubscribe('/test/channel')

callback = lambda{|m| p m}
client.subscribe('/channel', 77, &callback)
client.unsubscribe('/channel', &callback) 

```

Something like this... Bonus points for HTTP/2 ;p

**Comment by ramontayag** [comment]
We're building something similar too, but it puts the heavy lifting on a background worker.

https://github.com/bloom-solutions/message_bus_client_worker

It's not complete yet (no long polling).

**Comment by benlangfeld** [comment]
This is now on the master branch courtesy of https://github.com/SamSaffron/message_bus/pull/192. @SamSaffron It's going to be a couple of weeks before I have serious diagnostics improvements, so it may be worth releasing 2.2.0 with what we've got so far, and then a 2.3.0 in a few weeks time.

**Comment by SamSaffron** [comment]
Yeah I think we should release a 2.2.0 @tgxworld maybe once you are around can you push a new version?

**Comment by tgxworld** [comment]
2.2.0 has been released.
