### ISSUE TITLE
`site_id_lookup` returns nil causes rspec to crash

### ISSUE THREAD

**Issue by ramontayag** [SamSaffron/message_bus#196]
When the domain that is visited isn't a tenant in the app, we made `site_id_lookup` return `nil`. We noticed that when we ran specs, the Ruby process would most likely just die with "Process killed" and no reason. It took us a while to narrow down the issue (we were basically shooting in the dark) -- and found out that when we ensured that `site_id_lookup` didn't return nil, the Ruby process would not die.

I still don't know why the process would just die like that, and figured you would have a much better idea why.

If I were to guess where to fix the problem, it would be [here](https://github.com/SamSaffron/message_bus/blob/f9bc50f666d1cb98ea6094c531eacf6aa3f55d0a/lib/message_bus.rb#L563). Because if `site_id_lookup` is defined but returns `nil` when called, then a string like this would be returned:

```ruby
"#{channel}#{ENCODE_SITE_TOKEN}#{nil}"
```

**Comment by SamSaffron** [comment]
most likely due to keepalive interval and and something blocking in your test suite. 

Disable per: 

https://github.com/SamSaffron/message_bus/blob/master/lib/message_bus.rb#L544-L549

**Comment by ramontayag** [comment]
Thank you! I didn't check the `test.log` -- it's there. Messages like this are in the log:

```
Global messages on 10407 timed out, restarting process
```
