### ISSUE TITLE
Publish to MessageBus outside of Ruby/Rails?

### ISSUE THREAD

**Issue by tgodfrey** [SamSaffron/message_bus#203]
I am using MessageBus with a Rails app. It uses Redis for the storage backend.

We also have a microservice written in Elixir. We would like to use MessageBus for all of WebSocket communication between the server and browser. Is it possible to insert messages into Redis in such a way as to get MessageBus to publish it to the browser?

**Comment by SamSaffron** [comment]
Cross platform publish is surprisingly easy see:

https://github.com/SamSaffron/message_bus/blob/master/lib/message_bus/backends/redis.rb#L132-L184

There is a single LUA script should be very easy to port that routine somewhere else. 

Just keep in mind message bus does "chunked encoding long polling" this is different to websockets in quite a few ways. see: https://samsaffron.com/archive/2015/12/29/websockets-caution-required

**Comment by tgodfrey** [comment]
Thanks so much for the quick reply.

Here's a gist with my efforts, in case anyone else wants to do something similar: https://gist.github.com/tgodfrey/1a67753d51cb202ca8eb04b933cec924

**Comment by SamSaffron** [comment]
This is cool, maybe add a tiny note into the readme linking to it?
