### ISSUE TITLE
Long Polling Not Working In Production Behind Nginx

### ISSUE THREAD

**Issue by cheynewallace** [SamSaffron/message_bus#213]
Ok, im stuck..   I have long polling working fine locally, talking directly to my Rails app (Using Puma) although when I deploy to production, I can see the connection to the server, however no events are received until the next poll occurs, so im stuck waiting like 15 seconds for a message to come through.

I test this by manually triggering an event on the server, to which the client is subscribed to, and console log out the response.   Basically I see nothing, for about 15 seconds or so, then I'll see the post on the client to an endpoint like `<host>/message-bus/265582e80e9b4222baa3914fa217f32f/poll?_=3320` and then the message will appear in the console.  This continues to happen on subsequent messages, waiting another 15 seconds or so for a message to arrive. 

So its basically working like a regular short poll, which kind of defeats the purpose. Would really love some help, im trying to launch this app shortly.

Production is sitting behind an Nginx reverse proxy.  So I have a feeling this is my problem.

My Nginx Config looks like

```
upstream app {    
    server unix:/home/rails/app/current/tmp/sockets/puma.sock fail_timeout=0;
}

server {
  listen 443;
  server_name localhost 

  root /home/rails/app/current/public;
  try_files $uri/index.html $uri @app;

  include /etc/nginx/cloudflare.conf;

  location /message-bus/ {
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_pass http://app;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
  }

  location @app {
      proxy_pass http://app;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;

  }

  ssl on;
  ssl_certificate /home/rails/certs/default.crt;
  ssl_certificate_key /home/rails/certs/default.key;
```

Using client config (tried forcing on long poll, doesnt change anything)

```
    MESSAGE_BUS.callbackInterval = 15000;
    MESSAGE_BUS.enableLongPolling = true;
    MESSAGE_BUS.alwaysLongPoll = true;
```

I am using CloudFlare, but I have disabled it at this time while I figure out whats happening.

**Comment by cheynewallace** [comment]
For anyone else reading this, the problem seems to mostly go away when I set
```MessageBus.enableChunkedEncoding = false;``` on the client

**Comment by SamSaffron** [comment]
@cheynewallace  glad disabling chunked encoding worked for you, but my suspicion here is that something in your proxy chain is causing the problem. Disabling chunked encoding certainly can help for improperly configured proxy chains but it does add some extra costs.
