### ISSUE TITLE
"discourse" is hardcode in redis_channel_name of ReliablePubSub

### ISSUE THREAD

**Issue by tony612** [SamSaffron/message_bus#37]
in https://github.com/SamSaffron/message_bus/blob/master/lib/message_bus/redis/reliable_pub_sub.rb#L51

```rb
  def redis_channel_name
    db = @redis_config[:db] || 0
    "discourse_#{db}"
  end
```

Maybe we can have a solution to make this configrable?

**Comment by SamSaffron** [comment]
Sure its a bas prefix, lets just change it to _message_bus
