### ISSUE TITLE
Memory cleanup

### ISSUE THREAD

**Issue by RCM7** [SamSaffron/message_bus#40]
Hey there,

I'm currently toying a bit with message_bus because I'm seriously considering using it to be the communication bus of an application I'm developing.

After trying out, and searching a lot (even in discourse source code), I can't find where and if you do some memory clean-up of messages on redis.

Is it possible? What is the recommended way?

Thanks in advance!

**Comment by SamSaffron** [comment]
Already handled by 

https://github.com/SamSaffron/message_bus/blob/master/lib/message_bus/redis/reliable_pub_sub.rb#L30-L32

**Comment by RCM7** [comment]
Thanks! :)
