### ISSUE TITLE
How to publish data to all users except current one?

### ISSUE THREAD

**Issue by volontarian** [SamSaffron/message_bus#46]
Is there a way to just pass an user ID to the JavaScript method MessageBus.subscribe and the Ruby method MessageBus.publish and the current user becomes all updates except the updates "signed" with his user ID.

**Comment by SamSaffron** [comment]
Unclear on the use case here, can you explain.

On Sun, Aug 23, 2015 at 11:11 PM, Mathias Gawlista <notifications@github.com

**Comment by volontarian** [comment]
E.g. to avoid that if an user posts something then he should not get a message to automatically reload the route (in Ember.JS) because the user already sees the change.
Only changes from other users should reload the route.

But now I think it's easier to pass the author ID through the message data in the backend which publishes and check in the client if the author ID in the message data is the same as current user ID.

So the issue can be closed.

**Comment by dongli** [comment]
I also meet this case. It would be great if MessageBus can automatically filter the current user from the push list.

**Comment by SamSaffron** [comment]
Can you explain your exact use case?

**Comment by dongli** [comment]
In my case, `CommentsController#create` will publish message to `/comments` channel after calling `save`, and all the clients, which are viewing the comment page, subscribe the channel. The client which creates the comment is also included, so it will also get the notification, which is not necessary.

Currently, I put `user_id` of the comment in the message, and also set a `div` with `data-user-id` attribute to distinguish each client. When `data-user-id` equals `user_id` in the message, the notification will be ignored.

I found there is `user_id` in `MessageBus::Client`, but I have no idea how does it is used. Is it the same with the id of the login user? Or something else. There is no doc about it.

**Comment by SamSaffron** [comment]
The echo is actually kind of critical, otherwise you can not tell 100% that
your message was handled by the server, also ... if you we did any
filtering it would be to the client_id not user_id that may have multiple
clients.
