### ISSUE TITLE
"502 Bad Gateway" on unicorn USR2 restart

### ISSUE THREAD

**Issue by brauliobo** [SamSaffron/message_bus#48]
When about 10-15 message_bus' poll requests are made, the nginx reverse proxy in front of unicorn returns a 502 error. I've tried using `proxy_buffering off` but it didn't help.

Any clue why it is happening?

**Comment by SamSaffron** [comment]
not seeing this at all on Discourse, what server are you using, any more
details in the logs?

On Sat, Sep 5, 2015 at 7:40 AM, Bráulio Bhavamitra <notifications@github.com

**Comment by brauliobo** [comment]
nginx, unicorn (and unicorn worker killer, maybe it is this?) and rails 4.2.4

**Comment by brauliobo** [comment]
Yeah, I've confirmed the problem is with unicorn worker killer. Maybe document it on README

Also, If I restart the server the problem will also happen. Is it possible to keep the socket on nginx instead of keeping it with unicorn and rack.hijack?

**Comment by SamSaffron** [comment]
A single 502 is expected if you terminate the backend, but the client is resilient, it will not lose any data and just catch up as soon as the server restarts.

That said, strongly recommend against running unicorn killer

**Comment by brauliobo** [comment]
@SamSaffron Yeah, will have to memory_profiler on the app. I consider this closed, thanks!
