### ISSUE TITLE
message_bus setting document missing in README. Thanks.

### ISSUE THREAD

**Issue by zw963** [SamSaffron/message_bus#51]
Thank you give us a so awesome gem!

I have use this gem in our project several month, it work perfect.

I understood a little long pool,  But, I still not understood aboutwhat does the `callbackInterval` means, 
 I only notice the long-pool interval is 25 seconds, I can't search more info from issues, could you explain more about this in README ?

Thanks

**Comment by SamSaffron** [comment]
callbackInterval is the hard coded delay between long polls that get no data. it ensures that if the server starts misbahaving we will not aggressively poll it.

**Comment by zw963** [comment]
Thanks.

**Comment by feliperaul** [comment]
@SamSaffron I agree with @zw963 

In message_bus.rb you have:

```
def long_polling_interval
    @config[:long_polling_interval] ||= 25 * 1000
end
```

This appears to be a config option but it's not documented anywhere, it this is the setting that  determines how often the long poll requests last (looking at dev tools network tab, I see that each poll request lasts exactly 25 seconds). 

I have no idea what are the consequences of increasing or decreasing this value.

Also, documented in the readme, you have this:

// how often do you want the callback to fire in ms
MessageBus.callbackInterval = 500;

But I have changed this value and haven't seen any changes. My long poll requests still last 25 seconds.

What exactly these 2 options mean?

**Comment by SamSaffron** [comment]
> I have no idea what are the consequences of increasing or decreasing this value.

The reason for the magic number of 25 is that some proxies will shut down the channel at 30 so this just keeps stuff safer. 

In an HTTP/2 setup you could probably increase it a bit.  

callbackInterval is just a safeguard to ensure a client never floods a server.
