### ISSUE TITLE
Publish except to the current client_id

### ISSUE THREAD

**Issue by brauliobo** [SamSaffron/message_bus#52]
On a given action, I want to publish to all but not to the browser window that generated the event.

I know that the client_id is not know by Rails. Is there some way to make it known?

Then, `client_filter` should inform the `client_id` (I'm not sure, but maybe it is already on the `message` parameter?)

**Comment by SamSaffron** [comment]
its doable but a bit odd, it should be on the Client class anyway so in theory adding support for

```
MessageBus.publish "/foo", "bar", except_client_ids: ["xyz"]
```

that said, its not a trivial patch and you would have to test it carefully for perf. 

Why not simply ignore messages that come from you? The fact you get that message is an Ack that the server properly published it.

**Comment by brauliobo** [comment]
@SamSaffron How to ignore message using MessageBus javascript's API? Does the subscribe callback says the origin client_id? The case is that the user may have open another window on the same page, so only one client_id should be ignored.

**Comment by SamSaffron** [comment]
you are going to have to include the client id as part of the payload you
are publishing.

**Comment by SamSaffron** [comment]
I am rejecting this for now, I don't want to complicate the protocol to allow for this edge case, if you need to filter out delivery to a particular client then include the client id in the payload. we stream data back anyway as of 2.0 so impact is not high.
