### ISSUE TITLE
Site goes extremely slow when the browser connection limit (6) is reached

### ISSUE THREAD

**Issue by brauliobo** [SamSaffron/message_bus#54]
What do you do on discourse if the user open 6 tabs with six pages that uses message_bus? That will leave any empty connection slot for another work on the website, as currently browsers (chrome/firefox) has a limit of 6 connections per domain.

**Comment by brauliobo** [comment]
http://tools.ietf.org/id/draft-loreto-http-bidirectional-07.html#connectionlimit

**Comment by brauliobo** [comment]
using the dom storage to share only one long polling connection is a possible solution: http://meta.stackexchange.com/a/85045

**Comment by brauliobo** [comment]
a library as a solution for that: https://bitbucket.org/balpha/bytheway.js/src.

**Comment by brauliobo** [comment]
but it also seems simple to do it manually: http://blog.fastmail.com/2012/11/26/inter-tab-communication-using-local-storage/ (demo at http://www.nmjenkins.com/intertab.html)

**Comment by jnstq** [comment]
Is that necessary? When the tab isn't active messagebus will change from longpoll to polling every minute.

**Comment by brauliobo** [comment]
@jnstq and how for long will it keep the connection open?

**Comment by jnstq** [comment]
When the tab is not active, it's just a normal requests, it's fast. I don't know how long the connection is open, I guess that is managed by the browser.

**Comment by SamSaffron** [comment]
I do not think we cancel current requests when you open new tabs (need to
confirm by looking at code) , the long poll will expire within 29 seconds
and change to a poll.

it is conceivable that if you open 6 tabs in a row real fast you can cause
issues, but in practice that does not happen, regardless if we need to add
a .cancel we can its not a big deal.

**Comment by brauliobo** [comment]
@SamSaffron it is not about cancelling, it is about reuse of one long polling by all tabs.

**Comment by SamSaffron** [comment]
@riking has a work in progress PR that does that, it gets fairly tricky but
is doable

I do not want anything to break so it is going to take a while to test

**Comment by riking** [comment]
The PR doesn't cancel any requests, though, due to whatwg/fetch#27.

**Comment by SamSaffron** [comment]
I am closing this for now, 

If you run HTTP/2 which is my recommendation the 6 connections thing is a non issue. If you are not, well you have to work really hard to make it an issue due to the fallback. I am open to adding web workers but it is hellishly complex and not fully supported across platforms.
