### ISSUE TITLE
Clients deleted by timer queue preventing message delivery

### ISSUE THREAD

**Issue by robmonie** [SamSaffron/message_bus#55]
I'm seeing an issue where messages sometimes aren't being delivered immediately to clients. After some debugging, I believe what is happening is that the current client instance registered against a client_id in the connection_manager is being removed by timers from previous polls.  This is is particularly evident in our application because we tend to subscribe and unsubscribe to a number of different channels for short periods of time as a user works with the app. We're effectively simulating a request / response type pattern with an event_sourced / cqrs app using promises and short term message_bus subscriptions.

In more detail, the sequence of events that demonstrates this issue is as follows.

1. Subscribe to a channel
  - `middleware` creates a new client and adds it to the `connection_manager` 
  - `connection_manager` registers it against it's `client_id` in the `@clients` attribute of the `connection_manager`
  - `connection_manager` adds the `client_id` to the `@subscriptions` `set`.
  - `middleware` adds callback to the timers queue which calls `remove_client` in `long_polling_interval` seconds. 

2. User subscribes to another channel before the `long_polling_interval` has expired
 - `middleware` creates a new client and subscribes to both channels as above.

3. `long_polling_interval`  for the first subscription expires 
  - `remove_client` method on the `connection_manager` is called. 
  - the client registered against `@clients` in `connection_manager` for the `client_id` is removed. Note that this is actually removing the new client as the first client was replaced by a new client in step 2. This means that any messages published to either of these channels won't be delivered.

4. System publishes a message to the new channel subscribed to in step 2. 
  - No message is delivered to the browser because the client is no longer registered.

5. `long_polling_interval` expires on the client. It re-polls and probably catches up from the backlog. - Note that I haven't completely confirmed this yet.

I have been able to naively stop this problem from happening by checking the `connect_time` of the client being removed against the client currently registered in `@clients`. If they aren't the same i'm not removing the `client` from `@clients` or `client_id` form the `@subscriptions` but only cancelling the `cleanup_timer`. While this seems to help in basic testing, I suspect it may cause other cleanup issues due to remaining subscriptions.

I'll continue to investigate as best I can and update where I can but any thoughts on what i've found would be most appreciated. Especially if i'm off track on what I think i'm seeing.

**Comment by robmonie** [comment]
For reference, this commit has my basic change in it - https://github.com/hooroo/message_bus/commit/7788a52b1d6b75f66e1bb2b8fb2d560a765dce5a

This seems to be reliably returning messages to the client now but i'm unclear as to whether this has introduced other issues at this point.  Also, no meaningful test for this as yet.

**Comment by SamSaffron** [comment]
I think I understand the issue, can you do a PR for a test that exhibits the issue, the fix feels a bit hacky feels like a memory leak waiting to happen. 

also I wonder if this is somehow a js bug around usage, you really should not have 2 connections to the server going from one client at once.

**Comment by robmonie** [comment]
I'll see what I can do as far as a test for this. 

Just to clarify, there is only ever a single request polling at once.

The second request is the result of subscribing to a new channel while another is already subscribed. From what I remember, this causes the first  request to close and opens a new one including both channels in the request body.

**Comment by SamSaffron** [comment]
I don't think this test works quite right but I get the problem. 

.cancel in jQuery is async, just cause you call it does not mean stuff will cancel. So the following sequence it totally feasible, despite message-bus.js only working with one req at a time

1. Client A tries to subscribe to channels a,b
2. Client A tries to subscribe to channels c
3. subscribe to c handled by server
4 .subscribe to a,b handled by server 
5. 2 timeouts are in place 

The issue at the root is that the server needs to be aware of a sequence number from the client to ensure it only keeps track of timeouts and such on the most recent sequence ... working on a patch for this now.

**Comment by robmonie** [comment]
Great. Thanks for looking into this.
