### ISSUE TITLE
Can not start puma when set MessageBus.after_fork on boot work

### ISSUE THREAD

**Issue by embbnux** [SamSaffron/message_bus#57]
when I deploy my rails app in production with puma, puma socket cannot start if I add:
```ruby
on_worker_boot do
    MessageBus.after_fork
end
```
anything wrong? Thank you
log:
```ruby
[11443] Puma starting in cluster mode...
[11443] * Version 2.14.0 (ruby 2.2.3-p173), codename: Fuchsia Friday
[11443] * Min threads: 4, max threads: 16
[11443] * Environment: production
[11443] * Process workers: 1
[11443] * Phased restart available
[11443] * Listening on unix:///tmp/app.sock
[11443] * Daemonizing...
```
Ang Nginx cannot connect to unix:///tmp/app.sock

**Comment by SamSaffron** [comment]
Is anything in the logs? do you have redis installed?

**Comment by embbnux** [comment]
thank you, redis installed.puma do not log everything after [11443] * Daemonizing...,
but nginx cannot connect to puma socket.
If I remove 'MessageBus.after_fork' and restart, it works well

**Comment by SamSaffron** [comment]
Sorry for the late reply, what happens if you run it in not forking mode, does it work correctly?

**Comment by felixbuenemann** [comment]
@embbnux Add `require "message_bus"` just before the `on_worker_boot` block.

**Comment by SamSaffron** [comment]
yeah this has to be a user error, we work fine in a forked environment.

**Comment by SamSaffron** [comment]
we should probably update the readme though.

**Comment by embbnux** [comment]
thank you ! it work well

**Comment by jstdoit** [comment]
but, after I added the `require message_bus` in unicorn production mode, in browser, it got `404`
