### ISSUE TITLE
Restrict subscription to a channel?

### ISSUE THREAD

**Issue by namelessjon** [SamSaffron/message_bus#63]
Not sure on the best place to ask more support questions, but is there a way to restrict subscription to channel?

I'm looking at using message_bus for a chat type application, but there's also some internal messaging that would ideally go over the message bus (there's a message bus, why not use it?). However, I can't see any way to stop a chat client from subscribing to one of these internal channels, except by running them on a different message bus (e.g. db 1) or giving the channels "unguessable" names.

Is there something I'm missing?

**Comment by SamSaffron** [comment]
Sure you can ask here, simplest thing to do is publish the message to a restricted set of users (either to a group or specific users) 

```
MessageBus.publish("/ninja", "message", user_ids: [1,2,3], group_ids: [1,2,3])
```

Opaque channel names are at best security by obscurity.

**Comment by namelessjon** [comment]
I agree entirely that opaque channel names are security through obscurity, and that is definitely not my preferred solution.

The solution you suggested seems to require remembering to publish every internal message with the `:internal` group, or whatever, or it could potentially leak, which does seem fragile (vs not authorizing external subscription to the channel).  Am I right in reading that 'internal' clients (i.e. those directly using `MessageBus.subscribe`) automatically get all messages, regardless of group/user id for the message? (I see no API for a subscription only to messages from a particular group)

**Comment by SamSaffron** [comment]
Yes, internal clients get all messages, only external clients get filtered
on group/user.

The way message bus is designed one HTTP endpoint takes care of N
subscriptions, securing at the HTTP endpoint is possible, but you would
then have an all or nothing type design. It is wasteful to be polling N
endpoint for N channels.
