### ISSUE TITLE
Where do user_ids and group_ids get set?

### ISSUE THREAD

**Issue by jemminger** [SamSaffron/message_bus#64]
(is there some better place to ask for help?  Stackoverflow only has 12 followers of the "discourse" tag)

The readme shows this example:

```ruby
# messages can be targetted at particular users or groups
MessageBus.publish "/channel", "hello", user_ids: [1,2,3], group_ids: [4,5,6]
```

However it does not make it clear what specifically a "user_id" is or where it is set.  In my use case, I want to broadcast a message to a specific user.  Is the user_id the user's database ID, or something else?  

I suspect it's just some arbitrary identifier that I can just set into the current session and retrieve via 

```ruby
  MessageBus.user_id_lookup do |env|
    # return the user id here
  end
```

but I cannot seem to find the right place to put the `user_id_lookup` call where the rails session actually exists yet.  All I get for `env["rack.session"]` is `#<ActionDispatch::Request::Session:0x7fb788510dc8 not yet loaded>`

**Comment by SamSaffron** [comment]
run `rake middleware` to see where MessageBus is in the stack, you may want
to move it around to a more appropriate place if its too early in the
stack.

The most efficient spot for it is super early on, but you can always put it
way further down.

Once you sort this can you do a PR to improve the readme ?

**Comment by JAndritsch** [comment]
I managed to configure it via an initializer (config/initializers/message_bus.rb). My code looks something like this:

```
MessageBus.user_id_lookup do |env|
  # use the incoming env object to determine what this user's ID should be
  # ex:
    request = Rack::Request.new(env)
    request.cookies["user_id"]
end
```
In that example (which is definitely not the most secure way to do this), you parse the incoming ENV object into a Rack::Request, which then lets you ask for the request cookies, params, or even headers. 
This example expects that each user who connects with MessageBus will have their unique "user_id" cookie set at the time of the request. 

Again, not the most secure code since cookies can be altered but the example was meant to illustrate how this is done.

The same thing can be done with group identification. Here's a basic example:

```
MessageBus.group_ids_lookup do |env|
  # use the incoming env object to determine what groups this user should have
  # ex:
    request = Rack::Request.new(env)
    user_id = request.cookies["user_id"]
    user = User.find(user_id)
    user.roles # => [ "admin", "super user", "something else" ]
end
```
Does that help?

**Comment by SamSaffron** [comment]
> Does that help? 

yes it does :) we should get something to help cover this in the readme.

**Comment by SamSaffron** [comment]
Closing this cause there really is no bug here, @JAndritsch  can you review the readme to see if you feel it covers this in enough details?

**Comment by JAndritsch** [comment]
I remember be a bit confused myself when I first read the documentation on it. I'll work on submitting a PR to help make it more clear.

**Comment by ffabreti** [comment]
@JAndritsch, @SamSaffron : 

Can we access ActiveRecord models and retrieve request post params from inside user_id_lookup ? Something like:
```
req = Rack::Request.new(env)
if  SocialUser.validate_token(req.params["user_id"], req.params["user_token"])
   req.params["user_id"]
else
   nil
end
```

**Comment by jemminger** [comment]
@ffabreti AR models yes, provided they are in scope (works for me in an initializer).  Params maybe, in a quick test I did now it looks like the only params I get are those that the message_bus client-side js posts.
