### ISSUE TITLE
Authenticating messageBus requests

### ISSUE THREAD

**Issue by riqwan** [SamSaffron/message_bus#65]
Thanks for this amazing gem! 

We have an ember app with a token based authentication. I see that you generate a new clientID and register with message bus on every subscribe, safeguarding sniffing to an extent, but i failed to understand how authentication of these requests are done.

Assuming that my token has expired, or a new action has been performed by another user where the current user currently subscribed to the channel isn't authorized to access the data, I would still be receiving data from messageBus, which I don't think is ideal.

Is there a way we can return a 401 if the token was expired / user isn't authorized to receive data /didn't token exist in the request in the existing setup? What are your thoughts regarding this?

**Comment by SamSaffron** [comment]
You can subscribe to many channels. 

1. If you don't want anon to have access to ANY message bus goodness, seal off the /message-bus route, only allow authenticated users access

2. If you need to publish information privately include user_ids or group_ids when publishing the message per readme

3. be sure to implement user_id lookup from rack env in the callbacks 

MessageBus takes care of **not** allowing you access to any "private" messages, security is "per message" no "per channel" 

Can you perhaps submit a PR to improve the readme here?
