### ISSUE TITLE
Failed to process message

### ISSUE THREAD

**Issue by Vaporizd** [SamSaffron/message_bus#66]
Hi, 

I can't seem to get message_bus working. I get the following errors: https://gist.github.com/Vaporizd/398734438608301a39e0

What I do is:

```ruby
after_create :publish_entry

def publish_entry
  MessageBus.publish('/entries', "hello word")
end
```
I also can't seem to include the message-bus js lib
```
//= require message-bus
couldn't find file 'message-bus' with type 'application/javascript'
```

Full trace; https://gist.github.com/Vaporizd/f06bffade8b6490b338d
I've tried with both the 1.1.1 version and the newest 2.0 beta versions. Nothing seems to get that going. I have redis running and puma 

```ruby
require 'message_bus'
# Change to match your CPU core count
workers 1 

# Min and Max threads per worker
threads 1, 6

app_dir = File.expand_path("../..", __FILE__)

on_worker_boot do
  MessageBus.after_fork
end
```

Any help is appreciated, thanks.

**Comment by SamSaffron** [comment]
The particular bug is not really stopping anything from working I fixed it via:

https://github.com/SamSaffron/message_bus/commit/d761607aabfba7e7edbaf0783f9af0ff7ac22476

I assume you are not using rails or have a custom asset pipeline, if that is the case just source message-bus.js directly via: https://github.com/SamSaffron/message_bus/blob/master/assets/message-bus.js

Let me know how you go, PR to improve readme welcome.

**Comment by Vaporizd** [comment]
I managed to fix all issues with just restarting vagrant. However I'm not sure what the cause was. And I do use Rails. Also this PR should clear things a bit. #67

**Comment by SamSaffron** [comment]
closing as this is fixed
