### ISSUE TITLE
How does a server-to-server client process "catch up"?

### ISSUE THREAD

**Issue by marten** [SamSaffron/message_bus#69]
I'm evaluating this for our uses, but I wonder how something is supposed to work. From the README

```
MessageBus.subscribe "/channel" do |msg|
  # block called in a background thread when message is received
end

MessageBus.backlog "/channel", id
# returns all messages after the id
```

Let's say the client process has been offline for a bit (deployment or something). It knows where it was before stopping, so it can indeed request that backlog. However, it seems to me that:

* If you call backlog first, process that, and then subscribe, you'll miss any messages between the backlog and subscribing.
* If you call subscribe first, then process the backlog, you might get duplicates if any messages were published between subscribing (so processed by subscribe block) and calling `.backlog`.

I was expecting (hoping, really) that `subscribe` would take an optional id, and just call the block for the backlog and then start sending new messages as they come in. Since this is missing, what is the best way for a process to catch up and not miss anything or get duplicates?

**Comment by SamSaffron** [comment]
Yeah its a good point, perhaps do a PR for adding last_id to `subscribe` ?

**Comment by marten** [comment]
I'll see what I can do. Haven't done much in the way of writing tests for concurrency issues yet, so no promises.

**Comment by SamSaffron** [comment]
An initial implementation that tries to be correct and tests
non-multithreaded would be a great start! perhaps start there I can help
with the multi threading

**Comment by SamSaffron** [comment]
@jeremyevans  I wonder if this is something we want to add to 2.0, it is a bit of a hole in that you can not subscribe via server at a particular id

**Comment by jeremyevans** [comment]
@SamSaffron I believe all of the backends all support subscribing with an id and automatically yielding the backlog, I think this would be a good idea to support in the MessageBus API if it isn't supported already.

**Comment by ffabreti** [comment]
I've noticed `subscribe` returns nil.
Would be a simple approach to make subscribe return the last known message id for the channel, so that you would call `backlog` just after subscribing. Something like:
```
the_last_id = MessageBus.subscribe "/channel" do |msg|
    # block called in a background thread when message is received
end

MessageBus.backlog "/channel", the_last_id
     # returns all messages after the id
end
```

**Comment by ffabreti** [comment]
I've noticed `subscribe` returns nil.
Would be a simple approach to make subscribe return the last known message id for the channel, so that you would call `backlog` again if you missed any messages after subscribing. Something like:
```
my_last_id  #=> 740

MessageBus.backlog "/channel", my_last_id
     # process all messages after 740
     # sets my_last_id
end

my_last_id  #=> 750

the_last_id = MessageBus.subscribe "/channel" do |msg|
    # block called in a background thread when message is received
end

the_last_id #=>751

if the_last_id > my_last_id
     MessageBus.backlog "/channel", my_last_id
          # process all messages after 750
          # sets my_last_id
     end
end 

my_last_id #=> 751

```

**Comment by SamSaffron** [comment]
Implemented per:

https://github.com/SamSaffron/message_bus/commit/ae0d7cdaf0d645da65da7f1b2041f0e6d645305b

@jeremyevans this is the last change I wanted prior to 2.0, I feel the API is looking pretty good now. will let next beta bake for a few days and then do a final 2.0 release!

**Comment by jeremyevans** [comment]
@SamSaffron Looks good to me.
