### ISSUE TITLE
getting a 404 on the polling

### ISSUE THREAD

**Issue by karmajunkie** [SamSaffron/message_bus#70]
Everything works in development when I run with unicorn, without the addition to my unicorn.rb recommended in the readme. However, in production-like circumstances (our staging server) I'm seeing extremely long waits before a published message hits the client.  I'm running Rails 4.2 with the master branch of message_bus.

So, in an effort to get to the bottom of that, I made the addition to the unicorn configuration file, and immediately started having trouble. The first problem was that Rails complained about missing the `message-bus.js` asset, which I worked around by copying it out of the gem. Now I'm getting 404's on the polling requests. The output of `rake middleware` is as follows:

```
use Honeybadger::Rack::UserInformer
use Honeybadger::Rack::UserFeedback
use Honeybadger::Rack::ErrorNotifier
use Rack::Sendfile
use ActionDispatch::Static
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007fb3ec49fa50>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use BetterErrors::Middleware
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use MessageBus::Rack::Middleware
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
run MyApp::Application.routes
```

Any ideas of what I'm doing wrong here?

**Comment by SamSaffron** [comment]
are you running in a subfolder? 

Can you try bumping MessageBus::Rack::Middleware up to position 0?

**Comment by karmajunkie** [comment]
Not sure what you mean by running in a subfolder—the application is run via unicorn from the application root, with the config in `config/unicorn.rb`.

adding `config.middleware.insert_before 0, "MessageBus::Rack::Middleware"` to the end of my configuration block in `config/application.rb` does seem to fix the 404, and in my docker setup, which previously reproduced the delayed publish of messages we're experiencing in staging, I'm now seeing messages much more quickly. If the middleware positioning is an issue you'd like to track down I'm happy to leave this issue open.

**Comment by SamSaffron** [comment]
It is definitely related to positioning. I am not sure what to do here, going to close it. 

If we place ourselves too high, eg before the cookie store is initialized it takes a lot more work to figure out what user/group is accessing the bus. 

However, the higher up in the stack message bus is the better, ultimately you are going to be handling lots of requests there so forcing you to write a bit of extra code is probably the best thing. 

I am torn between having message bus insert itself in position 0 and leaving stuff as is.

**Comment by cannikin** [comment]
Can I re-open? I'm seeing a similar behavior that @karmajunkie is describing: works great in development, poll returns a 404 in production. I tried moving the middleware up:

    config.middleware.insert_before 0, MessageBus::Rack::Middleware

Which gives me:

    use Rack::MiniProfiler
    use Skylight::Middleware
    use Raven::Rack
    use MessageBus::Rack::Middleware
    use Rack::Sendfile
    use ActionDispatch::Executor
    use ActiveSupport::Cache::Strategy::LocalCache::Middleware
    use Rack::Runtime
    use Rack::MethodOverride
    use ActionDispatch::RequestId
    use RequestStore::Middleware
    use Rails::Rack::Logger
    use ActionDispatch::ShowExceptions
    use ActionDispatch::DebugExceptions
    use ActionDispatch::RemoteIp
    use ActionDispatch::Callbacks
    use ActionDispatch::Cookies
    use ActionDispatch::Session::CookieStore
    use MessageBus::Rack::Middleware
    use ActionDispatch::Flash
    use Rack::Head
    use Rack::ConditionalGet
    use Rack::ETag
    use OmniAuth::Builder
    run WNW::Application.routes

I see the request getting to nginx:

    172.31.39.254 - wnwqa [09/Jun/2016:01:12:55 +0000] "POST /message-bus/c99282531e15402281186595cfd9c140/poll HTTP/1.1" 404 579 "http://qa.workingnotworking.com/inbox/1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" - 0.000 X-Forwarded-For=72.192.153.253 Host=qa.workingnotworking.com

But nothing shows in the puma logs (and log_level is `:debug`). 

Anything else I can do to debug?

**Comment by cannikin** [comment]
Oh snap! Ignore: when I setup my nginx `location /message-bus/` rule I forgot the directive that actually forwards the request to puma. Whoops!

**Comment by paulanunda** [comment]
I'm seeing the same issue in a Rails 5.0 app deployed on Heroku. Running `heroku run rake middleware` returns:

```
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Timeout
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use Rollbar::Middleware::Rails::RollbarMiddleware
use ActionDispatch::RemoteIp
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use MessageBus::Rack::Middleware
use ActionDispatch::Flash
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
run AppName::Application.routes
```

This was not an issue during local development (using docker). Is there any risk to moving `use MessageBus::Rack::Middleware` to position 0?

**Comment by SamSaffron** [comment]
> This was not an issue during local development (using docker). Is there any risk to moving use MessageBus::Rack::Middleware to position 0?

Depending on what you do in the callbacks, if you add it too early you may not have all the setup you need done to figure out current user from env

**Comment by paulanunda** [comment]
That makes sense. Since i'm not doing anything w/ the current_user in the callback, but instead just using a UUID that's persisted in my db, i don't expect it to be an issue.

That being said, this wasn't an issue on Rails 4.2. Only in Rails 5. I wonder what changed :-(

**Comment by paulanunda** [comment]
Figured out what was wrong.

Changing my Procfile `web` entry from `web: bundle exec puma -C config/puma.rb ` to `web: bundle exec rails s` fix it, though I'm not quite sure why. The `config/puma.rb` is still loaded by `rails s` though.

**Comment by jstdoit** [comment]
we cannot simply add it add position `0`, cause it will break to use session or cookies...LOL

**Comment by jstdoit** [comment]
after some struggle, i removed `require 'message_bus'`( optional and `MessageBus.after_fork`), it works well.

**Comment by feliperaul** [comment]
@cannikin Could you please paste your /message-bus location block? I'm also having 404s.

**Comment by cannikin** [comment]
@feliperaul Do you mean the `after_fork` call in my puma config?

```ruby
on_worker_boot do
  ENV.update Dotenv::Environment.new('.env')
  ActiveRecord::Base.establish_connection
  MessageBus.after_fork
  Rails.cache.reset
end
```

Or the middleware location?

```ruby
use Raven::Rack
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use Sprockets::Rails::QuietAssets
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use BetterErrors::Middleware
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use MessageBus::Rack::Middleware
use ActionDispatch::Flash
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use OmniAuth::Builder
run WNW::Application.routes
```

**Comment by SamSaffron** [comment]
Is this a subdirectory setup?
