### ISSUE TITLE
Working with cURL (or without an official client)

### ISSUE THREAD

**Issue by uri** [SamSaffron/message_bus#78]
I've made a simple page that polls for a message:

```html+erb
<%= javascript_include_tag 'jquery' %>
<%= javascript_include_tag 'message-bus' %>
<h1>Test</h1>

<script type="application/javascript">
  MessageBus.start()

  MessageBus.callbackInterval = 500;
  MessageBus.subscribe("/channel", function(data){
    console.log(data)
  });
</script>
```

I'm using MessageBus with Rails 4.1, so I can bring up this page and in the rails console execute something like:

```ruby
MessageBus.publish '/channel', 'main channel'
```

This works great, everything as expected. However I'm trying to reproduce this with cURL (with the intension of then implementing it in iOS) but I cannot get the cURL request to work.

Here is the request I'm trying

```bash
curl \
       -v \
       -H "X-SILENCE-LOGGER: true" \
       -H "Connection: keep-alive" \
       -X POST \
       -d '{"/channel": -1, "__seq": 1}' \
       "http://api.local.com:3000/message-bus/myclientid/poll?"
```

Here is what my rails server outputs
```
Started POST "/message-bus/myclientid/poll" for 127.0.0.1 at 2016-03-03 15:42:31 -0500                                                                             
Delivering messages [] to client myclientid for user  (chunked)
# MessageBus.publish("/channel", "test")
Delivering messages [] to client myclientid for user  (chunked)
```

Here is the output from cURL

```
*   Trying 127.0.0.1...
* Connected to api.local.com (127.0.0.1) port 3000 (#0)
> POST /message-bus/myclientid/poll? HTTP/1.1
> Host: api.local.com:3000
> User-Agent: curl/7.43.0
> Accept: */*
> X-SILENCE-LOGGER: true
> Connection: keep-alive
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 28
>
* upload completely sent off: 28 out of 28 bytes
< HTTP/1.1 200 OK
< Cache-Control: must-revalidate, private, max-age=0
< Content-Type: text/plain; charset=utf-8
< Pragma: no-cache
< Expires: 0
< X-Content-Type-Options: nosniff
< Transfer-Encoding: chunked
< Connection: close
< Server: thin
<
[]
|
[]
|
* Closing connection 0
```

I'm going to try and implement this with ruby's Net::HTTP and see if I get the same problems there. I'm not an iOS dev, but I need to be able to explain how to long-poll outside of the JavaScript/Ruby clients.

**Comment by uri** [comment]
I was able to implement polling with Net::HTTP, so looks like I was on the right track. There must be something particular to cURL. I also tried copying the cURL request via Chrome dev tools and it still did not work.

Here is the Net::HTTP script I used for testing:

```ruby
require 'net/http'
require 'securerandom'

client_id = SecureRandom.uuid
uri = URI("http://api.local.com:3000/message-bus/#{client_id}/poll")

request = Net::HTTP::Post.new(uri)
request['X-SILENCE-LOGGER'] = 'true'
request.set_form_data( '/channel' => -1, '__seq' => 1 )

Net::HTTP.start(uri.hostname, uri.port) do |http|
  http.request(request) do |response|
    response.read_body do |chunk|
      print chunk
    end
  end
end
```

**Comment by SamSaffron** [comment]
cool, also linked from the readme there is a ruby client, you could use that. not sure what is going on with curl there.

**Comment by uri** [comment]
@SamSaffron I was basically in the mindset of, if I can make it work with curl, I can make it work anywhere, with the ultimate goal of getting working on iOS.

**Comment by SamSaffron** [comment]
It should totally work from curl, there is no reason why not, can you do some "puts" debugging in the middleware to see what is being passed in.

**Comment by uri** [comment]
The only difference I was able to find was that with cURL I was setting the body to a JSON payload, but in my Ruby script I was using form data. Will investigate further.

**Comment by SamSaffron** [comment]
we are looking at adding json payload support so this should sort this out.
