### ISSUE TITLE
Application got very slow with passenger installed with nginx

### ISSUE THREAD

**Issue by michalhorcic** [SamSaffron/message_bus#79]
Hello,

gem works like a charm, unfortunately I experience very slow behaviour on production with passenger.

So far I am not able to find out the reason. Only thing I know, when I disable subscribe on client, everything is fast again. Otherwise it waits like 2-3 seconds before response. Even in rails log is nothing during that waiting.

Can the reason be that passenger is running in only one process?

Do you have any experience with running it with passenger?
Passenger was installed with nginx, so it is not standalone. So my nginx.conf looks like this.
server {
        listen       80;
        server_name  medis.rails.timepress.cz;
        root /home/www/medis/public;
        passenger_enabled on;
    }

I will be glad for any help. Thanks.

**Comment by jeremyevans** [comment]
Can you try adding the following to the nginx configuration: `proxy_http_version 1.1;`  Additionally, you would want to disable proxy buffering for message_bus responses.

@SamSaffron You can disable proxy buffering for nginx on a per-request using `X-Accel-Buffering: no` header.  Not sure if that is something we want to do by default or support via an option.

**Comment by SamSaffron** [comment]
> Can the reason be that passenger is running in only one process?

Unlikely to be the reason, hijack is meant to work fine. Most likely the buffering like @jeremyevans said , we should totally add the header here: https://github.com/SamSaffron/message_bus/blob/master/assets/message-bus.js#L124

I know @foobarwidget recently added some patches to passenger to support hijack properly, can you ensure you are running latest?

**Comment by jeremyevans** [comment]
@SamSaffron The `X-Accel-Buffering` header is a response header, not a request header, so it will need to be set in the rack middleware.  It's also nginx-specific, so you may not want to set it by default.

**Comment by SamSaffron** [comment]
Makes sense, we can possibly detect nginx via env and then automatically
set, or simply document and in readme

**Comment by michalhorcic** [comment]
Thank you for hints. Unfortunately I wasn't able to make passenger work for me.
I tried these nginx settings:
server {
  listen 80;
  server_name nameOfServer;
  root /home/www/medis/public;
  passenger_enabled on;
  proxy_buffering off;
  proxy_http_version 1.1;
}

then I tried running passenger standalone with nginx as a proxy:
server {
	listen       80;
        server_name  nameOfServer;
        location / {
          proxy_pass http://127.0.0.1:3001;
          proxy_set_header Host $host;
          proxy_buffering off;
  	  proxy_http_version 1.1;
        }
    }

With very same results as before. Few requests are fast as expected, then one is very slow and then again.

I have passenger version 5.0.20, and on another server passenger 5.0.25.

My solution for now will be running app on thin server, with nginx proxy. That works very well.
Thanks.

**Comment by SamSaffron** [comment]
wait with the "slow" requests are they to message bus? keep in mind, by
design, message bus long polls and streams. So its expected you would have
a bunch of slow requests.

**Comment by michalhorcic** [comment]
No no, I mean classic request, ie. when I click on link in menu to another section in my app. Then I need to wait seconds before anything happens. And rails log is empty. So I guess it is waiting somewhere in nginx/passenger. After those few seconds, logs shows classic rails rendering of html and send it to browser.

**Comment by FooBarWidget** [comment]
@michalhorcic 

> proxy_buffering off;
> proxy_http_version 1.1;

These settings don't do anything to Passenger. They only affect the Nginx proxy module. But if I were to consider what you meant to do:

- The 'buffering' option is unnecessary when using Passenger. Passenger performs buffering *and* forwards data in real-time to the client, at the same time, without any configuration.
- Passenger already fully supports all HTTP 1.1 features, without any configuration.

Maybe you're looking for this? https://www.phusionpassenger.com/library/config/nginx/tuning_sse_and_websockets/

**Comment by michalhorcic** [comment]
@FooBarWidget 
Thanks a lot. 
That is exactly what I was looking for. Now everything works.
As my passenger is older (5.0.20) I added to application.rb:

```
if defined?(PhusionPassenger)
  PhusionPassenger.advertised_concurrency_level = 0
      
  #And then according to message_bus documentation:
  PhusionPassenger.on_event(:starting_worker_process) do |forked|
    if forked
      MessageBus.after_fork
    else
    end
  end
end
```
Now updates are instant and application is fast. Thank you all for help.

**Comment by SamSaffron** [comment]
@michalhorcic  perhaps you can do a PR to update the readme here?
