### ISSUE TITLE
MessageBus.unsubscribe does not seem to work in JS client

### ISSUE THREAD

**Issue by dlupu** [SamSaffron/message_bus#83]
Hello, 

I've tested the following in the console : 

```javascript
MessageBus.callbacks.length // 1
var f = function(data) { console.log('test'}}
MessageBus.subscribe('/test', f)
MessageBus.callbacks.length // 2
MessageBus.unsubscribe('/test', f)
MessageBus.callbacks.length // 2 (should have been 1 !!)
```

==> `MessageBus.unsubscribe` does not seem to work

**Comment by dlupu** [comment]
I just realised i forgot to specify the version : I'm using v.1.1.1

**Comment by maxjacobson** [comment]
Is the idea that `unsubscribe` removes a callback or that it adds a callback when a user to fire when a user leaves a page? (Sorry for hijacking your thread -- I'm not sure why it's not working, but I was also just reading the docs and kind of confused by this feature)

**Comment by dlupu** [comment]
Hello @maxjacobson the documentation is unclear on what the second parameter of the `unsubscribe` should be. 

The implementation makes me think that it should be the initial callback (the one that has been provided to subscribe) and that's what I have used in my code example above.

Though It would be easier if the `subscribe`function would return a callback to fire when the user leaves à page (or, in my case, when unmounting a React component).

**Comment by SamSaffron** [comment]
Confirmed ... something here is buggy ... debugging

**Comment by SamSaffron** [comment]
Ok, the issue was that we were making an internal copy, these means the array we were leaking out was the original array. 

Fixed the implementation, also cleaned up the return values (which were odd due to a old and ugly coffee script migration) 

Not sure if I want to return a callback to unsubscribe directly, though I am open to allowing:

MessageBus.subscribe("/channel", function(msg) { }).unsubscribe() ... I like that API, want to submit a PR for it? 

Note:

We really want some tests for the javascript parts, will add a request for help in the readme.

**Comment by dlupu** [comment]
@SamSaffron first of all I just wanted to say thank you for this library and for your commitment on maintaining it. It's rare to see gems with so rapid responses and fixes from the owner.

Thank you for the fix, If I understand correctly, I need to use the master branch in order to benefit of it, right?

As for the API, what you have suggested seems ok : `MessageBus.subscribe("/channel", function(msg) { }).unsubscribe()`. Its very explicit.

I don't have a lot of free time right now but, nevertheless, I'm willing to take 2h next and contribute to this gem. I could start for instance adding some tests for the JS part using teaspoon and jasmine, if that's ok with you.

**Comment by SamSaffron** [comment]
Thanks @dlupu  

At the moment we are working on getting a test framework in via: https://github.com/SamSaffron/message_bus/pull/86 perhaps once it is merged in you can have a quick look. 

To access the fix you can just install the beta gem, I published it
