### ISSUE TITLE
Question: is it possible to get, on subscribe, the messages that were published previously ?

### ISSUE THREAD

**Issue by dlupu** [SamSaffron/message_bus#87]
I would like to be able, on subscribe from the JS, to get messages that were published in the previous 60 seconds prior to the subscribe.

Is it possible to do that with message bus? I saw you can pass a last Id to the subscribe function so I said to myself:
* lets use a timestamps as message id
* when subscribing, pass the timestamp corresponding to 60.seconds.ago

But in order for this to work
* MessageBus should allow me to set messages id
* MessageBus should not complain if the timestamp I'm passing as a lastid does not correspond to any message (because no message was published with that exact timestamp)

Would this be possible ?  Can you suggest any alternative solution ?
Thanks you.

**Comment by SamSaffron** [comment]
Can you expand on the exact reason you need this use case so I can get my head around it?

**Comment by dlupu** [comment]
We use message bus in order to get events from the server and animate parts of then  screen based on those events. Animations last for 60 seconds.

So in order to see the animations, the screen must have been open before the occurence of the event that triggered that animation.

I'm looking for a way to display events that happened just before accessing the page (which are often the reason why the user access that page). Being able to replay the last events from the server would allow us to do that!

**Comment by SamSaffron** [comment]
I feel that what you are needing here is a mechanism of placing a "time cap" on the backlog for a particular channel. If message bus is ONLY used for this feature you could set it globally via: `max_backlog_age` 

I support adding this kind of feature on a per-channel basis but it is a bit tricky.

**Comment by dlupu** [comment]
Since I don't really care about messages that have more than 1 minutes, the `max_backlog_age` could be what I was looking for. 

One more question: if  I setup `max_backlog_age` to `60` how can I get, via the JS client, all events in the backlog ?

**Comment by SamSaffron** [comment]
Sure, subscribe at position 0

**Comment by dlupu** [comment]
Great! Thanks
