### ISSUE TITLE
Long polling not working?

### ISSUE THREAD

**Issue by rpbaltazar** [SamSaffron/message_bus#88]
From my understanding of long polling (and forgive me if i'm wrong) it should make the request once and wait until the server has something to answer.

I've made a quick setup on my application, and as soon as I subscribe to the channel, if i look at browser network inspector, I see multiple requests being sent (depending on the polling frequency) even though the server has not published anything to that channel.

Am I misinterpreting the way long polling works, have I not configured it properly, or is it a bug?

**Comment by SamSaffron** [comment]
I am not seeing this, can you attach some screenshots from chrome... the process usually is:

1. you poll on a bunch of channels all of which are position -1
2. a chunked encoding long poll starts, server tells client what the position is on each channel
3. long poll ends

1-3 happen in one long poll that takes 30 secs or so 

Only reason you would see multiple reqs is if you are subscribing to new channels after the long poll started or you can not use chunked encoding for some reason.

**Comment by SamSaffron** [comment]
can you include some chrome dev tools screenshots or HAR files?

**Comment by rpbaltazar** [comment]
Will do ASAP. Maybe later today. Sorry for the delays

**Comment by SamSaffron** [comment]
I am closing this for now, need more info to debug this, also need it tested on latest beta
